### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by CsarRamos** [mjwconsult/civicrm-contributiontransactlegacy#1]
Hello @mattwire,
I tried the extension and works perfectly, solve the error. Would it be possible to launch a tag?
Thanks!

**Comment by mattwire** [comment]
@CsarRamos Here you go! https://github.com/mjwconsult/civicrm-contributiontransactlegacy/releases/tag/0.1

**Comment by CsarRamos** [comment]
> @CsarRamos Here you go! https://github.com/mjwconsult/civicrm-contributiontransactlegacy/releases/tag/0.1

Perfect, tx!
